apiVersion: v1
kind: Service
metadata:
  name: akka-cluster-demo-nodeport
  labels:
    app: akka-cluster-demo
spec:
  selector:
    app: akka-cluster-demo
  type: NodePort
  ports:
    - port: 8080
      # nodePort: <31514>
